import fs from "fs";

//TODO: Use the list generated by getCitiesDataSCript.js
const ourCities = []

const cities = [];
const countries = [];

ourCities.forEach((city) => {
  cities.push({
    countryCode: city.countryCode,
    population: city.population,
    location: { latitude: city.latitude, longitude: city.longitude },
    name: city.name,
  });

  const isCountryAlreadyInList = countries.some(
    (country) => country.countryCode === city.countryCode
  );

  if (!isCountryAlreadyInList)
    countries.push({
      countryCode: city.countryCode,
      name: city.country,
      flag: city.flag,
      currency: city.currency,
    });
});

fs.writeFile("new_cities.json", JSON.stringify(cities), (err) => {
  if (err) {
    console.error("Error writing file:", err);
    return;
  }
  console.log("Cities file created successfully!");
});

fs.writeFile("countries.json", JSON.stringify(countries), (err) => {
  if (err) {
    console.error("Error writing file:", err);
    return;
  }
  console.log("Countries file created successfully!");
});
