name: Auto Assign Issue to Project

on:
  issues:
    types: [opened]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue to Project
        run: gh issue edit ${{ github.event.issue.number }} --add-label Startup-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
